version: "3.8"

services:
  db:
    image: postgres:15
    container_name: crm_sto_db
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_sto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: crm_sto
      DB_USER: crm_user
      DB_PASSWORD: crm_pass

volumes:
  postgres_data:
